api/urls.py
from api.models import CategoryResource, CourseResource
from tastypie.api import Api
from django.urls import path, include

api = Api(api_name='v1')
api.register(CourseResource())
api.register(CategoryResource())

# api/v1/courses/       GET, POST
# api/v1/courses/1/     GET, DELETE
# api/v1/categories/    GET
# api/v1/categories/1/  GET

# For POST, DELETE and header
# Key: Authorization
# Value: ApiKey admin:asdhlk2345678901

urlpatterns = [
    path('', include(api.urls), name='index'),
]

base/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('api/', include("api.urls")),
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:course_id>', views.single_course, name='single_course')
]

api/models.py
from tastypie.resources import ModelResource
from tastypie.authorization import Authorization
from shop.models import Category, Course
from .authentication import CustomAuthentication

class CategoryResource(ModelResource):
    class Meta:
        queryset = Category.objects.all()
        resource_name = 'categories'
        allowed_methods = ['get']

class CourseResource(ModelResource):
    class Meta:
        queryset = Course.objects.all()
        resource_name = 'courses'
        allowed_methods = ['get', 'post', 'delete']
        excludes = ['reviews_qty']
        authentication = CustomAuthentication()
        authorization = Authorization()
    
    def hydrate(self, bundle):
        bundle.obj.category_id = bundle.data['category_id']
        return bundle

    def dehydrate(self, bundle):
        bundle.data['category_id'] = bundle.obj.category
        return bundle

    def dehydrate_title(self, bundle):
        return bundle.data['title'].upper()

shop/models.py
from django.db import models
from django.utils import timezone

class Category(models.Model):
    title = models.CharField(max_length=255)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

class Course(models.Model):
    title = models.CharField(max_length=300)
    price = models.FloatField()
    students_qty = models.IntegerField()
    reviews_qty = models.IntegerField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=timezone.now)
    
    def __str__(self):
        return self.title

api/views.py
from django.shortcuts import render

# Create your views here.

shop/views.py
from django.shortcuts import render, get_object_or_404
from django.http import Http404
from .models import Course


def index(request):
    courses = Course.objects.all()
    return render (request, 'shop/courses.html', {'courses': courses})

def single_course(request, course_id):
    # OPTION 1
    # try:
    #     course = Course.objects.get(pk=course_id)
    #     return render (request, 'single_course.html', {'course': course})
    # except Course.DoesNotExist:
    #     raise Http404()

    # OPTION 2
    course = get_object_or_404(Course, pk=course_id)
    return render (request, 'shop/single_course.html', {'course': course})

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <title>{% block title %}{% endblock  %}</title>
</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
        <div class="container">
            <a href={% url "shop:index" %} class="navbar-brand">Courses Shop</a>
            <span class='navbar-text'>
                <a href="/admin/" class='me-2' target='_blank'>Admin</a>
                <a href="/api/v1/" target='_blank'>API</a>
            </span>
        </div>
    </nav>
    <main class="container">
        {% block  content%}
        {% endblock  %}
    </main>
</body>
</html>

templates/shop/courses.html
{% extends "base.html" %}
{% block title %}All courses{% endblock  %}

{% block content %}
<table class='table mt-5 table-bordered table-striped table-hover'>
    <thead class='table-dark'>
        <tr>
            <th>Title</th>
            <th>Category</th>
            <th>Price</th>
            <th>Students Quantity</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {%for course in courses%}
        <tr>
            <td>
                {% comment %} <a href={{course.id}}>{{course.title}}</a> {% endcomment %}
                {% comment %} <a href={% url "single_course" course.id %}>{{course.title}}</a> {% endcomment %}
                <a href={% url "shop:single_course" course.id %}>{{course.title}}</a>
                
            </td>
            <td>{{course.category}}</td>
            <td>{{course.price}}</td>
            <td>{{course.students_qty}}</td>
            <td><button class='btn btn-primary'>Buy</button></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock content %}

templates/shop/single_course.html
{% extends "base.html" %}
{% block title %}{{course.title}}{% endblock  %}

{% block content %}
    <h1 class='mt-5'>{{course.title}}</h1>
    <h2>{{course.category}}</h2>
    <p>Price: {{course.price}}</p>
    <p>Students Quantity: {{course.students_qty}}</p>
    <button class='btn btn-primary'>Buy</button>
{% endblock content %}